# Generated by Django 5.1.7 on 2025-03-30 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField()),
                ('close_price', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('official_name', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(max_length=50)),
                ('subtype', models.CharField(max_length=50)),
                ('available_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('current_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('currency_code', models.CharField(blank=True, max_length=10, null=True)),
                ('mask', models.CharField(blank=True, max_length=4, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.account'),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=500)),
                ('item_id', models.CharField(max_length=255, unique=True)),
                ('institution_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
